name: CI - Backend

on:
  push:
    tags:
      - 'v*'
    branches:
      - 'main'
    paths:
      - 'backend/**'

env:
  REGISTRY: ghcr.io

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r backend/requirements.txt

      - name: Syntax check
        run: python -m py_compile backend/main.py

      - name: Lint
        run: |
          pip install ruff
          ruff check backend/

      - name: Type check
        run: |
          pip install mypy
          mypy backend/ --ignore-missing-imports --exclude backend/tests --no-namespace-packages 



  build-scan-push-backend:
    runs-on: ubuntu-latest
    needs: test-backend
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Extract version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build backend image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository }}/backend:${{ steps.version.outputs.VERSION }} \
            -t ghcr.io/${{ github.repository }}/backend:latest \
            ./backend

      - name: Scan backend image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ github.repository }}/backend:${{ steps.version.outputs.VERSION }}
          format: table
          severity: CRITICAL,HIGH
          exit-code: 0

      - name: Push backend image
        run: |
          docker push ghcr.io/${{ github.repository }}/backend:${{ steps.version.outputs.VERSION }}
          docker push ghcr.io/${{ github.repository }}/backend:latest

      - name: Update backend manifest in infra repo
        run: |
          git clone https://x-access-token:${{ secrets.MANIFESTS_TOKEN }}@github.com/sadokkhessairi/k3s-infra.git
          cd k3s-infra/manifests/app-manifests
          sed -i "s|image: ghcr.io/.*/backend:.*|image: ghcr.io/${{ github.repository }}/backend:${{ steps.version.outputs.VERSION }}|" backend-deployment.yaml
          git config user.email "ci@github.com"
          git config user.name "GitHub Actions"
          git add backend-deployment.yaml
          git commit -m "ci: update backend image to ${{ steps.version.outputs.VERSION }}"
          git push
